<div class="preview_invitation" style="border-bottom-color:rgb(226, 225, 225);border-bottom-style:solid;border-bottom-width:1px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(226, 225, 225);border-left-style:solid;border-left-width:1px;border-right-color:rgb(226, 225, 225);border-right-style:solid;border-right-width:1px;border-top-color:rgb(226, 225, 225);border-top-style:solid;border-top-width:1px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:500px;margin-bottom:0px;margin-left:47px;margin-right:47px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:900px;">
    <div class="preview_invitation_top" style="background-attachment:scroll;background-clip:border-box;background-color:rgb(81, 184, 55);background-image:none;background-origin:padding-box;background-position-x:0%;background-position-y:0%;background-repeat-x:;background-repeat-y:;background-size:auto;border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:40px;line-height:40px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:900px
;">
        <span style="border-bottom-color:rgb(255, 255, 255);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(255, 255, 255);border-left-style:none;border-left-width:0px;border-right-color:rgb(255, 255, 255);border-right-style:none;border-right-width:0px;border-top-color:rgb(255, 255, 255);border-top-style:none;border-top-width:0px;color:rgb(255, 255, 255);display:inline;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:auto;line-height:40px;margin-bottom:0px;margin-left:20px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:auto
;">{{config('app.web_name')}}</span>
    </div>
    <div class="preview_invitation_left fleft" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;float:left;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:12px;height:300px;margin-bottom:0px;margin-left:20px;margin-right:0px;margin-top:20px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-align:center;text-size-adjust:100%;width:200px;">
        <dl>
            <dd class="preview_invitation_left_user" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:12px;height:221px;list-style-image:none;list-style-position:outside;list-style-type:none;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-align:center;text-size-adjust:100%;width:200px;-webkit-margin-after:0px;-webkit-margin-before:0px;-webkit-margin-end:0px;-webkit-margin-start:0px;">
                <img src="{{$app_url}}{{$user->avatar}}" alt="" style="width: 180px;height: 180px;"/><br />
                {{$user->username}}
            </dd>
            <dd style="margin-top: 3px;border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:12px;height:221px;list-style-image:none;list-style-position:outside;list-style-type:none;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-align:center;text-size-adjust:100%;width:200px;-webkit-margin-after:0px;-webkit-margin-before:0px;-webkit-margin-end:0px;-webkit-margin-start:0px;">{{$user->work}}/{{$user->school}}</dd>
        </dl>
    </div>
    <div class="preview_invitation_right fleft" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;float:left;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:300px;line-height:25px;margin-bottom:0px;margin-left:20px;margin-right:0px;margin-top:20px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:630px;">
        <p style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:25px;line-height:25px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:630px;-webkit-margin-after:0px;-webkit-margin-before:0px;-webkit-margin-end:0px;-webkit-margin-start:0px;0pxuser agent stylesheetp">HI,</p>
        <p style="margin-top: 10px;border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:25px;line-height:25px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:630px;-webkit-margin-after:0px;-webkit-margin-before:0px;-webkit-margin-end:0px;-webkit-margin-start:0px;0pxuser agent stylesheetp">&nbsp;&nbsp;&nbsp;&nbsp;我是{{$user->username}}，{!!get_content('24')!!}</p>
        <p style="margin-top: 20px;border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:25px;line-height:25px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:630px;-webkit-margin-after:0px;-webkit-margin-before:0px;-webkit-margin-end:0px;-webkit-margin-start:0px;0pxuser agent stylesheetp">{!!get_content('21')!!}
        </p>
        <div class="invite_fuyan" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:80px;line-height:30px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:30px;text-size-adjust:100%;width:630px
;">
            <span class="fleft" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;float:left;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:60px;line-height:30px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:400px
;">
                邀请附言：<br />
                {{ $content }}
            </span>
            <span class="fright" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;float:right;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:83px;line-height:30px;margin-bottom:0px;margin-left:0px;margin-right:100px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:86px
;">
                {!!get_content('23')!!}
            </span>
        </div>
        <p class="clear" style="height: 20px;clear:both">
            <p style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:25px;line-height:25px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:630px;-webkit-margin-after:0px;-webkit-margin-before:0px;-webkit-margin-end:0px;-webkit-margin-start:0px;0pxuser agent stylesheetp">请你点击一下链接，接受好友邀请：</p>
            <p style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);display:block;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:25px;line-height:25px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;width:630px;-webkit-margin-after:0px;-webkit-margin-before:0px;-webkit-margin-end:0px;-webkit-margin-start:0px;0pxuser agent stylesheetp"><a href="{{ route('invitation.show',['uid' => $user->id]) }}" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:none;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:none;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:none;border-top-width:0px;color:rgb(0, 0, 0);cursor:auto;display:inline;font-family:微软雅黑, Arial, Helvetica, sans-serif;font-size:14px;height:auto;line-height:25px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-decoration-color:rgb(0, 0, 0);text-decoration-line:none;text-decoration-style:solid;text-size-adjust:100%;width:auto
;">{{ route('invitation.show',['uid' => $user->id]) }}</a></p>
        </p>
    </div>
    <div class="clear" style="height: 20px;clear:both"></div>
    <div class="clear preview_invitation_footer" style="height: 100px;border-top: 1px #e2e1e1 solid;">
        <p style="margin-left: 50px;margin-top: 20px;line-height: 35px;font-size: 18px;">{!!get_content('23')!!}</p>
    </div>
</div>
